### ISSUE TITLE
开发者您好，市场宽度的计算为何需要truncate_table，每次运算都要删库重新计算呢?

### ISSUE THREAD

**Issue by aoxiansheng** [bankrollhunter/market-breadth#14]
开发者您好，市场宽度的计算为何需要truncate_table，每次运算都要删库重新计算呢?

**Comment by hk-Lei** [comment]
为了重新获取所有的数据，不然的话可能有复权的问题存在

aoxiansheng ***@***.***> 于2021年3月24日周三 下午8:23写道：

**Comment by aoxiansheng** [comment]
感谢解惑！明白了！
